solution("dons_script")
configurations({"Debug", "Release", "Analyze"})
linkoptions({"-static"})
flags({"StaticRuntime"})

configuration("Debug")
flags({"Symbols"})
buildoptions({"-g"})
configuration("Release")
flags({"OptimizeSpeed"})
configuration("Analyze")
buildoptions({"--analyze"})
configuration({})

project("path")
kind("StaticLib")
language("C++")
buildoptions({"-std=c++0x"})
files({"libmain.cpp", "grid.cpp", "node.cpp", "edge.cpp"})

project("test_path")
kind("ConsoleApp")
language("C++")
buildoptions({"-std=c++0x"})
links({"path"})
files({"main.cpp"})